"""initial migration

Revision ID: 5038ba623d31
Revises: 
Create Date: 2026-01-11 21:33:41.786956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5038ba623d31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('chinese_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('words', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('cme1', 'cme2', 'cme3', 'cme4', 'cme5', 'all_lvl', name='level'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocab_list', sa.String(length=128), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('date_time_start', sa.String(), nullable=True),
    sa.Column('date_time_end', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiplayer_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('game_code', sa.Integer(), nullable=True),
    sa.Column('vocab_list_id', sa.Integer(), nullable=False),
    sa.Column('game_board_state', sa.JSON(), nullable=True),
    sa.Column('scoreboard', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vocab_list_id'], ['vocab_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiplayer_game_players',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['multiplayer_game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplayer_game_players')
    op.drop_table('multiplayer_game')
    op.drop_table('game')
    op.drop_table('vocab_list')
    op.drop_table('user')
    # ### end Alembic commands ###
